"""initial schema

Revision ID: adab00e43363
Revises: 
Create Date: 2026-07-30 01:05:29.514015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adab00e43363'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('councils',
    sa.Column('council_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('resolution_count', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('council_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('delegate1', sa.Text(), nullable=True),
    sa.Column('delegate2', sa.Text(), nullable=True),
    sa.Column('delegate3', sa.Text(), nullable=True),
    sa.Column('delegate4', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='countryrole'), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('speaker_points', sa.Integer(), nullable=False),
    sa.Column('amendments_submitted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('secretariat',
    sa.Column('secretariat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('secretariat_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country_council',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.council_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_id', 'council_id')
    )
    op.create_table('resolutions',
    sa.Column('resolution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('clauses', sa.Integer(), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.Integer(), nullable=True),
    sa.Column('seconder', sa.Integer(), nullable=True),
    sa.Column('negator', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='resolutionstatus'), nullable=False),
    sa.Column('amendment_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.council_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['negator'], ['countries.country_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seconder'], ['countries.country_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitter'], ['countries.country_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resolution_id')
    )
    op.create_table('amendments',
    sa.Column('amendment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('amendment_number', sa.Integer(), nullable=False),
    sa.Column('clause_number', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('submitter', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='amendmentstatus'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.resolution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter'], ['countries.country_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('amendment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amendments')
    op.drop_table('resolutions')
    op.drop_table('country_council')
    op.drop_table('secretariat')
    op.drop_table('countries')
    op.drop_table('councils')
    # ### end Alembic commands ###
